version: '2'
services:
  mastermind:
    image: registry.heroku.com/lucas-mastermind-game/web:0.0.1-SNAPSHOT
    environment:
      PORT: 8081
    ports:
      - 8081:8081
  database:
    image: postgres
    environment:
        POSTGRES_DB: mastermindgame
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres@123
        PORT: 5432
    ports:
      - 5432:5432
    container_name: postgres

